"use client"; // This is a client component 👈🏽

import { createContext, useEffect, useState } from 'react'

//components
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { lookInSession } from '@/common/SessionFunc';


import { Inter } from "next/font/google";

//css
import "./globals.css";


const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

//creating UserContext
export const UserContext = createContext({})

export default function RootLayout({ children }) {

  const [userAuth, setUserAuth] = useState({})

  useEffect(() => {


    let userInSession = lookInSession("user")
    userInSession ? setUserAuth(JSON.parse(userInSession)) : setUserAuth({ token: null })

  }, [])

  return (
    <html lang="en">
      <body className={inter.className}>
        <UserContext.Provider value={{ userAuth, setUserAuth }}>
          <Navbar />
          {children}
          <Footer />
        </UserContext.Provider>
      </body>
    </html>
  );
}
